### ISSUE TITLE
Add lineSeparator parameter to configuration

### ISSUE THREAD

**Issue by comdiv** [mojohaus/license-maven-plugin#106]
Now we are building code on mix Windows/Linux dev environment, so license plugin cause invalid delta generating CRLF on one system and LF on Linux

We want to specify that we have to use only LF

Suggest to use lineSeparator in configuration with default value from System.getProperty

**Comment by ragadeeshu** [comment]
I just want to chime in, I am also facing the same problem, our builds has a tendency to fail on windows because of this.

**Comment by tchemit** [comment]
I guess you are talkin about license update header mojo ?
I just add a new property **lineSeparator** to specify what you need. It is use then while generating license header.

**Comment by tchemit** [comment]
@comdiv, @ragadeeshu I just deployed a snapshot with this new feature.
Could you please confirm it is working fine for you ? If you need some help to use snapshot, let me know I can help.
Thanks.

**Comment by comdiv** [comment]
Nice think it closes

**Comment by tchemit** [comment]
@comdiv have you try the snapshot ? I will start a release 1.16, could you please test in the staging repository when it will be ready ?
If you don't know how to do this, I can help, it is quite simple. thanks

**Comment by tchemit** [comment]
@comdiv here it is :) Release 1.16 is in vote (see https://groups.google.com/d/topic/mojohaus-dev/xZoobcYx-n8/discussion)

**Comment by Wykiki** [comment]
Hello, I got hard-time configuring this property.
It looks like that the `lineSeparator` property for `license-maven-plugin` expect a character LF, not a placeholder like `LF` or `\n` (in the case I want to use LF as line separator).

I do not see in the documentation how to do it, and tried with that :

```xml
<license.lineSeparator>LF</license.lineSeparator>
<license.lineSeparator>\n</license.lineSeparator>
<license.lineSeparator>0x0A</license.lineSeparator>
```

Thank for your answer !

**Comment by johny2000uwb** [comment]
I have the same problem as @Wykiki too. Please add some example, how should be this value used. I have tried almost everything but each value will be printed direct into text.
