### ISSUE TITLE
Support for tycho Plugin

### ISSUE THREAD

**Issue by grigortonkov** [mojohaus/license-maven-plugin#11]
I have a maven project based on the tycho plugin. 
the dependency are resolved by tycho using the manifest.mf files. 
I want to use the license-maven-plugin to collect the licences. 
Please provide solution hot to do it. 

Example pom file.

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>XXX</groupId>
	<artifactId>framework.god</artifactId>
	<version>1.0.0.Lokal</version>
	<packaging>pom</packaging>

	<properties>
		<tycho-version>0.21.0</tycho-version>
	</properties>
	
	<repositories>
		<repository>
			<id>luna</id>
			<layout>p2</layout>
			<url>http://download.eclipse.org/releases/luna/ </url>
		</repository>

		<repository>
			<id>efxclipse-runtime</id>
			<layout>p2</layout>
			<url>http://download.eclipse.org/efxclipse/runtime-released/1.1.0/site</url>
		</repository>
	</repositories>

	<build>
		<resources>
			<resource>
				<directory>css</directory>
			</resource>
		</resources>

		<testSourceDirectory>src</testSourceDirectory>

		<plugins>

			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>target-platform-configuration</artifactId>
				<version>${tycho-version}</version>
				<configuration>
					<pomDependencies>consider</pomDependencies>
					
					
					<environments>
						<environment>
							<os>win32</os>
							<ws>win32</ws>
							<arch>x86</arch>
						</environment>
						
						<environment>
							<os>win32</os>
							<ws>win32</ws>
							<arch>x86_64</arch>
						</environment>
					</environments>

				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-maven-plugin</artifactId>
				<version>${tycho-version}</version>
				<extensions>true</extensions>
			</plugin>

			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-compiler-plugin</artifactId>
				<version>${tycho-version}</version>
				<configuration>
					<encoding>UTF-8</encoding>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>				
			</plugin>

			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-source-plugin</artifactId>
				<version>${tycho-version}</version>
				<executions>
					<execution>
						<id>plugin-source</id>
						<goals>
							<goal>plugin-source</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

						 
		 <plugin>
		   <groupId>org.codehaus.mojo</groupId>
		   <artifactId>license-maven-plugin</artifactId>
		   <version>1.6</version>
		   <configuration>
		   <licensesOutputFile>C:\\licences\view3-framework1.xml</licensesOutputFile>
		   </configuration>
		   <executions>
				 <execution>
				   <id>default-cli</id>
				   <phase>package</phase>
				   <configuration>
						<licenseMerges>
						  <licenseMerge>The Apache Software License, Version 2.0|Apache License, Version 2.0|Apache Public License 2.0</licenseMerge>
						</licenseMerges>
				   </configuration>
				 </execution>
		   </executions>
		 </plugin>
		 
		</plugins>
	</build>
	
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>junit</groupId>
				<artifactId>junit</artifactId>
				<version>4.4</version>
				<scope>test</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
</project>

**Comment by tchemit** [comment]
@grigortonkov I don't know at all tycho dependencies resolver, I will have a look about it.

**Comment by tchemit** [comment]
License maven plugin is written for maven usage, we won't include any support for other tycho plugin here, sorry. But if you provide us a good patch with this support we will be glad to include it. thanks.
