### ISSUE TITLE
Extra whitespace in Apache license text

### ISSUE THREAD

**Issue by pettermahlen** [mojohaus/license-maven-plugin#114]
I'm having a problem using this plugin together with https://github.com/coveo/fmt-maven-plugin. The latter (based on https://github.com/google/google-java-format) mandates that there should be no trailing white space characters on lines, whereas the Apache license file adds that. So either the formatting check breaks, or the license check breaks (because the license plugin requires the extra white space). The problematic lines are:

```
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
```

Ideally, I think the plugin shouldn't add the unnecessary whitespace before and after the URL. Alternatively, I think the check goal should trim the lines before comparing, so trailing whitespace is ignored. Is this feasible?

**Comment by pettermahlen** [comment]
Just noticed #99, which seems to address the same issue. I saw the builds are failing, but don't understand why. Is this something I could help out with?

**Comment by tchemit** [comment]
@pettermahlen Hi, I know that issue is a pain in the ass, I will ahev a look at it soon

**Comment by ppalaga** [comment]
A PR with an integration test is welcome.

**Comment by jamesagnew** [comment]
A note to anyone else who finds this ticket: The feature added in #99 seemed to resolve this for me! This is awesome.

**Comment by ppalaga** [comment]
`trimHeaderLine` sounds like a valid solution. Closing.
