### ISSUE TITLE
Cleaner third-party aggregate on multi license projects

### ISSUE THREAD

**Issue by diegosalvi** [mojohaus/license-maven-plugin#115]
Original grouped third-party file third-party-file-groupByLicense.ftl is annoying when multilicensed libs kicks in (each is listed multiple times).

A new third-party file with a cleaner listing could be helpful.

Like:

```
(license A, License B)
    libA
    libB
    ...

(license A, License C)
    ...

(license B)
    ...

```

**Comment by ppalaga** [comment]
The fix seems to have been merged. Feel free to reopen if that's not the case.
