### ISSUE TITLE
aggregate-add-third-party scope not limited to the project it's executed in

### ISSUE THREAD

**Issue by tazle** [mojohaus/license-maven-plugin#12]
*Aggregate-add-third-party* goal aggregates licenses of all dependencies of all projects in the reactor build instead of the dependencies of the project it's executed in.

For example, consider the following project structure:
* parent (pom)
  * project1 (pom, executes *aggregate-add-third-party* plugin in 'compile' phase)
    * project1-code (jar, depends on hibernate)
  * project2 (pom, executes *aggregate-add-third-party* plugin in 'compile' phase)
    * project2-code (jar, depends on eclipselink)

If I run `mvn package` in project1 *aggregate-add-third-party* plugin reports project1-code's dependencies, which is as expected. Same for project 2.

If I instead run `mvn package` in parent, so that project1 and project2 are both built in the same reactor, the executions of *aggregate-add-third-party* plugin in project1 and project2 both report all the dependencies of project1-code and project2-code combined. It appears that *aggregate-add-third-party* gathers all the dependencies in the reactor for its report rather than just the dependencies of the project in which it is executed.

**Comment by tchemit** [comment]
@tazle I am not quite sure you are using the aggregate goal as it should be. IMHO aggregate mojo should always and only be used on a parent pom but never on his children. I will have a closer look at your problem.

**Comment by tchemit** [comment]
aggregate-third-party-mojo is designed to be used only on root maven project. If you want to execute it on each project modules level, use the thid-party-mojo instead.

I will close this issue since I can't figure out what to do. You can reopen this issue, including a test project to explain the defect. Thanks.
