### ISSUE TITLE
SPDX license identifiers

### ISSUE THREAD

**Issue by matrixik** [mojohaus/license-maven-plugin#125]
Would be nice to have option to output file with licenses using they SPDX identifier.

More info:
https://spdx.org/
https://spdx.org/licenses/

**Comment by ppalaga** [comment]
A pull request is welcome.

**Comment by ppalaga** [comment]
Here is the list of SPDX licenses: https://github.com/spdx/license-list-data/blob/master/json/licenses.json

**Comment by ppalaga** [comment]
@matrixik which mojos is this supposed to affect?

**Comment by matrixik** [comment]
Hmm, actually I don't remember why I created this issue, sorry.

**Comment by ppalaga** [comment]
Closing this one as missing any goal. See https://github.com/mojohaus/license-maven-plugin/issues/247 and https://github.com/mojohaus/license-maven-plugin/issues/250 that are related to SPDX.

**Comment by matrixik** [comment]
Thank you.
