### ISSUE TITLE
aggregate-add-third-party for version 1.14 and 1.15 not working

### ISSUE THREAD

**Issue by daudazimkhan** [mojohaus/license-maven-plugin#126]
I tried to run the following:

- mvn org.codehaus.mojo:license-maven-plugin:1.12:aggregate-add-third-party
- mvn org.codehaus.mojo:license-maven-plugin:1.13:aggregate-add-third-party
- mvn org.codehaus.mojo:license-maven-plugin:1.14:aggregate-add-third-party
- mvn org.codehaus.mojo:license-maven-plugin:1.15:aggregate-add-third-party

But only 1.12 and 1.13 worked. For 1.14 and 1.15 the following errors were reported (Deleting local repo didn't work)

**1.14:**
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:1.14:aggregate-add-third-party (default-cli) on project dcoll-app-ufc-services: could not execute goal AggregatorAddThirdPartyMojo for reason : Can't find license-maven-plugin -> [Help 1]

**1.15:**
[WARNING] The POM for org.codehaus.mojo:license-maven-plugin:jar:1.15 is missing, no dependency information available
.......
[ERROR] Plugin org.codehaus.mojo:license-maven-plugin:1.15 or one of its dependencies could not be resolved: Failure to find org.codehaus.mojo:license-maven-plugin:jar:1.15 in http://artifactory.XXXXX.net:XXXX/artifactory/remote-repos was cached in the local repository, resolution will not be reattempted until the update interval of remote-repos has elapsed or updates are forced -> [Help 1]

**Comment by tchemit** [comment]
Hi @daudazimkhan , could you give us a project to confirm the defect. Thanks

**Comment by daudazimkhan** [comment]
Hi @tchemit, thanks for looking into this. You can reproduce this with any maven project e.g. [this one](https://github.com/diegoneuralo/maven.git). Clone it and remove the target directory. Then try running the following:

- mvn org.codehaus.mojo:license-maven-plugin:1.13:aggregate-add-third-party

The above is for **v1.13** and it **works**. Now try it for v1.15 by running the following:

- mvn org.codehaus.mojo:license-maven-plugin:1.15:aggregate-add-third-party

This one (**v1.15**) **fails**.

**Comment by tchemit** [comment]
@daudazimkhan , the project you gave me is not a multi-module project, so you can't use the aggregate mojo on it.

Can you give me another example project? thanks.

**Comment by jeacott1** [comment]
same problem, still get this with 2.0.0

**Comment by thermaleagle** [comment]
I got it on a multimodule project today as well with 2.0.0

**Comment by tchemit** [comment]
I will have a look to it soon.

I was away from this project from too long. I see there is some work to do here.

I hope a end-of-the-year release. 

Feel free to reopen any issue. :)

**Comment by martinleim** [comment]
@thermaleagle : I had the same issue as you. I fixed it by adding the plugin to the `pluginManagement` section of the project - even though I did specify any configuration:
```xml
<build>
        <pluginManagement>
            <plugins>
              <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <version>2.0.0</version>
            </plugin>
          </plugins>
    </pluginManagement>
</build>
```

**Comment by mpriha** [comment]
I needed to put the `pluginManagement` section into the main `pom.xml` file where I define the modules to get this working. But now the issue is that the `executions` section where I specify the configuration does not apply at all.

**Comment by mpriha** [comment]
> I needed to put the `pluginManagement` section into the main `pom.xml` file where I define the modules to get this working. But now the issue is that the `executions` section where I specify the configuration does not apply at all.

I needed to move the `configuration` section from under 'execution' to the main level like this and seems to work now

[plugin-config-sample.txt](https://github.com/mojohaus/license-maven-plugin/files/11380232/plugin-config-sample.txt)
