### ISSUE TITLE
'remove-file-header' goal leaves the '\n' character, which should be avoided.

### ISSUE THREAD

**Issue by xeagle2** [mojohaus/license-maven-plugin#129]
Hello there,

When the RemoveFileHeaderMojo removes the license it calculates the lastChar of '\n'

```
while ( lastchar != '\n' )
{
            lastchar = content.charAt( ( ++lastIndex ) );
}
```

A few lines lower there is a concatenation

`String contentWithoutHeader = content.substring( 0, firstIndex ) + content.substring( lastIndex );`

where **substring** method takes the lastIndex inclusive which is '\n'.

**Comment by ppalaga** [comment]
The fix seems to have been merged. Feel free to reopen if that's not the case.
