### ISSUE TITLE
licenseMergesFile should also support remote urls

### ISSUE THREAD

**Issue by TorstenKruse** [mojohaus/license-maven-plugin#132]
At the moment "licenseMergesFile" only supports files from local file system.

It would be great if also remote urls were supported like it is done for "missingFileUrl". Even a new parameter "licenseMergesFileUrl" like it was done for "missingFileUrl" would be fine

Then we would be able to consolidate the license merges for all projects in one file which could be used from all projects.

And of course the feature should be available also via pom.xml not just cli as the documentation says.

**Comment by tchemit** [comment]
Good idea, I will add a **licenseMergesUrl** and deprecates the **licenseMergesFile**.

**Comment by TorstenKruse** [comment]
Great. Thanks a lot.
