### ISSUE TITLE
Can't use any url in missingFileUrl

### ISSUE THREAD

**Issue by tchemit** [mojohaus/license-maven-plugin#134]
The actual code is:
```
     if (HttpRequester.isStringUrl(missingFileUrl))
            {
                String httpRequestResult = HttpRequester.getFromUrl(missingFileUrl);
                unsafeMappings.load(new ByteArrayInputStream(httpRequestResult.getBytes()));
            }
```
which fails if you use for example a file url.

**Comment by ppalaga** [comment]
Which mojos are affected?

**Comment by nfalco79** [comment]
> Which mojos are affected?

All mojos with missingFileUrl attribute are affected by this:
- add-third-party
- aggregate-add-third-party
- aggregate-third-party-report
- third-party-report
