### ISSUE TITLE
"Can't find license-maven-plugin" in 1.16 if plugin isn't configured in the POM

### ISSUE THREAD

**Issue by digulla** [mojohaus/license-maven-plugin#139]
If you try to run `mvn license:aggregate-add-third-party` without adding the plugin to the root / parent POM first, you get the error `Can't find license-maven-plugin` throws in this line:

https://github.com/mojohaus/license-maven-plugin/blob/70b96dfd6db8b5bde085567ea3cb2ef1bdef2d83/src/main/java/org/codehaus/mojo/license/AggregatorAddThirdPartyMojo.java#L197

I see two solutions:

1. Enhance the error message: "Please add the plugin to your POM"
2. Put the three values in a property file (using resource filtering) and load that file from the classpath.

**Comment by ppalaga** [comment]
Thanks for the report. A PR with an integration test is welcome.

**Comment by rkraneis** [comment]
Why is this closed as completed? This issue still persists :/
