### ISSUE TITLE
aggregate-add-third-party should not depend on project packaging

### ISSUE THREAD

**Issue by TorstenKruse** [mojohaus/license-maven-plugin#144]
The aggregate-add-third-party actually only runs for project with packaging pom.

As we would like to define the default build goals in parent pom, we need to use aggregate-add-third-party for single and multi module projects.

So I would be helpful to get aggregate-add-third-party running also for single module projects with a packaging different from pom (like jar or war).

Probably a flag "acceptNonPomPackaging" on aggregate-add-third-party goal (where acceptPomPackaging seems to be redundant since it will only execute on pom packaging at the moment) would be an option to preserve current behaviour but let developers configure the plugin to their needs.

**Comment by jimonthebarn** [comment]
Just out of curiosity: Why not just use the add-third-party goal as well?

**Comment by TorstenKruse** [comment]
Thanks for the hint. I'll try.

**Comment by ppalaga** [comment]
`add-third-party` mojo should work in the sketched situation. Feel free to reopen if it does not.
