### ISSUE TITLE
license-maven-plugin interferes with project dependencies

### ISSUE THREAD

**Issue by jimonthebarn** [mojohaus/license-maven-plugin#145]
Hey guys,

I ran into an interesting problem I could not solve by myself and was wondering whether you could chime in and help. Its seems that the license-maven-plugin interferes (a dependency of my project even though declared as compile time dependency is skipped entirely) with maven dependencies in certain project setups.

I created a small project portraying the setup and the issue:
https://github.com/jimonthebarn/maven-license-plugin-issue

Could you please take a look?

**Comment by derKrischan** [comment]
I've got the same behaviour. Took me hours to figure out that the license-plugin caused my build to fails because the classes in submodul1 are not found while compiling sumbodule2 as reactor build from parent pom. License plugin is configured to execute aggregate-add-third-party in default phase.

**Comment by jimonthebarn** [comment]
Friendly reminder. :)

**Comment by jimonthebarn** [comment]
@derKrischan Have you found a solution that is not based upon removing the plugin altogether?

**Comment by derKrischan** [comment]
@jimonthebarn : No, I haven't found a solution yet.

**Comment by tchemit** [comment]
Hi guys, I will try to find some time to help you later in the week.
Sorry to be so away from this right now.
