### ISSUE TITLE
Exclusions don't seem to work

### ISSUE THREAD

**Issue by bstopp** [mojohaus/license-maven-plugin#16]
When running `mvn license:update-file-header`
Configured with:

```xml
<groupId>org.codehaus.mojo</groupId>
<artifactId>license-maven-plugin</artifactId>
<version>1.5</version>
<configuration>
  <licenseName>apache_v2</licenseName>
  <addJavaLicenseAfterPackage>false</addJavaLicenseAfterPackage>
  <excludes>
    <exclude>*.js</exclude>
  </excludes>
</configuration>
```

Still processes my JS files. Also tried:

```xml
<exclude>**/vendor/**/*.js</exclude>
<exclude>**/vendor/**</exclude>
<exclude>**/*.js</exclude>   
```

I'm really just trying to get it to not process my vendor provided files, but test cases are showing nothing working yet.

**Comment by tchemit** [comment]
@bstopp I just try on version 1.9 and it works fine to me. I changes the integration test `update-file-header-test-mojo` to prove this.

I tried with 

` <exclude>**/*.js</exclude>`

and 

` <exclude>**/aPath/*.js</exclude>`
