### ISSUE TITLE
update-file-header changes file permissions: clears executable bit

### ISSUE THREAD

**Issue by ninowalker** [mojohaus/license-maven-plugin#166]
I am running `license:update-file-header`; one of the files is a `.sh` with mode 755. After running, even though there is no change to the contents, the permissions are changed:

```
+ mvn ... license:update-file-header
...
[INFO] Scan 14 files header done in 44.889ms.
[INFO] 
 * update header on 14 files.

+ git status
Changes not staged for commit:
...
	modified:   bin/run.sh

+ git diff
diff --git a/bin/run.sh b/bin/run.sh
old mode 100755
new mode 100644
```

Note the permissions changed, but the contents did not! (Because the file is already correct)

**Comment by ppalaga** [comment]
An integration test reproducing the issue in https://github.com/mojohaus/license-maven-plugin/tree/master/src/it would be highly welcome.

**Comment by rez-** [comment]
I tried to make an integration test but I cannot...
Somehow, when the invoker prebuild script runs, it detects that the file is not executable while it should! The file is executable, but Java/groovy is unable to determine that it is.

Furthermore, I only noticed that the file permission is changed only when the contents is changed (a new header is applied).

**Comment by gevegab** [comment]
As far as I can understand the code, the **UpdateFileHeaderMojo** works, by making a copy of the original file, adding the header to the copy, and finally deleting the original file and renaming the copy :

https://github.com/mojohaus/license-maven-plugin/blob/e427a5c08f15f6ad7e2e7cf83268ecda19045724/src/main/java/org/codehaus/mojo/license/AbstractFileHeaderMojo.java#L737-L764

So it is not surprising that file permissions get lost in the processing.

After some debugging I think the fix has to be done in this method

https://github.com/mojohaus/license-maven-plugin/blob/e427a5c08f15f6ad7e2e7cf83268ecda19045724/src/main/java/org/codehaus/mojo/license/utils/FileUtil.java#L156-L176

I am not familiar with manipulating file attributes in Java, but after some stackoverflow search I thing you could  use

`java.nio.file.Files.getPosixFilePermissions` and `java.nio.file.Files.setPosixFilePermissions` to copy the permissions.

I develop in Windows and the combination git+windows makes painful for me to provide a test, but I hope this helps
