### ISSUE TITLE
remove strange warning about aggregateMissingLicensesFile

### ISSUE THREAD

**Issue by TorstenKruse** [mojohaus/license-maven-plugin#207]
I have a multi-module project and use the aggregate-add-third-party goal. 

I always get "You should use missingFile parameter instead of deprecated aggregateMissingLicensesFile." for the main project (not for each module) although I use missingFile instead of aggregateMissingLicensesFile.

Looking into code, probably aggregateMissingLicensesFile still has its default value and won't be null at any time?

**Comment by ppalaga** [comment]
Probably easy to fix. A PR is welcome.

**Comment by nfalco79** [comment]
@ppalaga you can close also this issue. Covered by #284

**Comment by ppalaga** [comment]
@TorstenKruse this should be fixed in 1.18 that will appear in ~72 hrs. Feel free to reopen if it is not fixed there.
