### ISSUE TITLE
Upgrade to doxia 1.8

### ISSUE THREAD

**Issue by Tibor17** [mojohaus/license-maven-plugin#217]
The plugin uses old Doxia 1.5 which caused 
ClassNotFoundException `org/apache/maven/doxia/sink/render/RenderingContext`.
It makes problems to run on Maven 3.3.9 and JDK 1.8.

**Comment by ppalaga** [comment]
Could you please try to reproduce with a SNAPSHOT built from the current master now after https://github.com/mojohaus/license-maven-plugin/pull/220 was merged? 

I tested manually with maven 3.5.4 and 3.6, but not with 3.3.x
