### ISSUE TITLE
add license header after DOCTYPE in html files

### ISSUE THREAD

**Issue by heapifyman** [mojohaus/license-maven-plugin#22]
As far as I know older Internet Explorer versions seem to have trouble with html files that contain comments (e.g. the license header) **before** the DOCTYPE.

Is there a way to configure the plugin to add the license header **after** the DOCTYPE for html files?

Like it is already done for XML files where the header is added after the ```<?xml .... ?>```

**Comment by tchemit** [comment]
@heapifyman enjoy this new feature in version 1.9 ;).
