### ISSUE TITLE
Dates in license header are not updated

### ISSUE THREAD

**Issue by heapifyman** [mojohaus/license-maven-plugin#23]
Hi,

it's a whole new year. If my license header from last year read e.g.:
```Copyright 2012 - 2015 ... ```
shouldn't it be updated to:
```Copyright 2012 - 2016 ... ```
when I (edit and) rebuild the project now?

**Comment by mpkorstanje** [comment]
It should [and it does](https://github.com/mpkorstanje/simmetrics/commit/0a195751b2bdbb29248aea5081ddceb87cbc61b3#diff-a5999b765622a72744dd031494aa4889). But you have to configure it to configure it with <canUpdateCopyright>true</canUpdateCopyright>.

			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>license-maven-plugin</artifactId>
				<version>1.8</version>
				<configuration>
					<verbose>false</verbose>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>update-file-header</goal>
						</goals>
						<phase>process-sources</phase>
						<configuration>
							<organizationName>Simmetrics Authors</organizationName>
							<canUpdateLicense>true</canUpdateLicense>
							<canUpdateCopyright>true</canUpdateCopyright>
							<canUpdateDescription>true</canUpdateDescription>
							<addJavaLicenseAfterPackage>false</addJavaLicenseAfterPackage>
							<licenseName>apache_v2</licenseName>
						</configuration>
					</execution>
				</executions>
			</plugin>

**Comment by heapifyman** [comment]
You're right, of course. I missed that in the documentation.
Thanks.

Follow-up question: it is not possible to "update" the ```processStartTag``` and ```processEndTag``` once a license header has been added to a file, is it?

**Comment by mpkorstanje** [comment]
Nope. You'd have to remove the licence first but as is you'll have to create a pull request with that functionality first.

**Comment by heapifyman** [comment]
But there is no ```remove``` goal in the plugin, right? So I'd have to manually remove the existing license headers?

**Comment by mpkorstanje** [comment]
Yup. Either that or add it to the plugin. But I'm not sure about the state of the project atm. Some prs are getting merged but not a whole lot of activity otherwise.

**Comment by tchemit** [comment]
Hi, I will cut a release 1.9 today (or starts it...). the projet is back on track, so stay tuned :)
I close this issue since there is nothing more to do on it.
