### ISSUE TITLE
aggregate-third-party-report goal fails when licenseMerges parameter is used

### ISSUE THREAD

**Issue by elballa** [mojohaus/license-maven-plugin#258]
Usage of licenseMerges parameter is cause of failure in the aggregate-third-party-report goal.
It happens because licenseMerges is a list of strings and it's passed as second argument in the
loadProjectArtifacts method of DependenciesTool class which expects a list of remote repositories instead.

**Comment by ppalaga** [comment]
Thanks for the report. An integration test reproducing the issue under https://github.com/mojohaus/license-maven-plugin/tree/master/src/it and a fix is welcome.
