### ISSUE TITLE
Add timeout parameters to AbstractDownloadLicensesMojo

### ISSUE THREAD

**Issue by ppalaga** [mojohaus/license-maven-plugin#278]

**Comment by nfalco79** [comment]
Please consider also to use those parameters also to configure the HTTP client that download any Url parameter

**Comment by ppalaga** [comment]
> Please consider also to use those parameters also to configure the HTTP client that download any Url parameter

It is out of the current scope. Feel free to open a separate issue for UrlRequester and send a PR. BTW UrlRequester also does not support HTTP proxies.
