### ISSUE TITLE
licenseMergeUrl parameter produces unreliable result in all report goals

### ISSUE THREAD

**Issue by elballa** [mojohaus/license-maven-plugin#291]
licenseMergeUrl parameter produces unreliable result in report goals if there is more then one raw in the content of linked file

**Comment by elballa** [comment]
Hi @ppalaga, do you think there could be possibility to include this fix in the next 1.18 release?

**Comment by ppalaga** [comment]
No, 1.18 is about to pass the vote today at 8:28:39 PM UTC+1. Nothing can be changed during the vote. 1.19 is your sole hope.

**Comment by elballa** [comment]
When do you plan to release 1.19?

**Comment by ppalaga** [comment]
Soonish, probably when I finish https://github.com/mojohaus/license-maven-plugin/pull/295

**Comment by elballa** [comment]
Thanks!
