### ISSUE TITLE
Plans for a 1.9 release

### ISSUE THREAD

**Issue by maggu2810** [mojohaus/license-maven-plugin#30]
Hello,
are there already plans for a new release?
At which time I could expect a official 1.9 that contains the last commits?

**Comment by tchemit** [comment]
Hi @maggu2810 , I will try to start a release next week.

**Comment by maggu2810** [comment]
Glad to hear. Thank you :wink:

**Comment by maggu2810** [comment]
Any news?

**Comment by maggu2810** [comment]
ping @tchemit

**Comment by tchemit** [comment]
@maggu2810 ... ok next week was this week-end ;).
