### ISSUE TITLE
Upgrade to Maven 3 APIs and Aether

### ISSUE THREAD

**Issue by srdo** [mojohaus/license-maven-plugin#326]
It would be good to upgrade to Maven 3 APIs and Aether. It is difficult to implement some features (programmatic dependency resolution for instance) correctly with the old APIs, and they are also deprecated in newer Maven versions.

The plugin could be upgraded to use Maven 3 dependencies, and maven-resolver (Aether).

**Comment by brabenetz** [comment]
Is the exact Maven Version "3.5.4" really needed?
I had  a problem with Travis-CI which seems to use Version "3.5.2":
https://travis-ci.org/brabenetz/secured-properties/jobs/588693548

**Comment by srdo** [comment]
@brabenetz See https://github.com/mojohaus/license-maven-plugin/pull/327. It's possible the plugin may work with 3.5.2. Oldest version tested was 3.5.4 through this repo's Travis setup. It's odd that yours is using an older Maven.

You could try reducing the version to 3.5.2 and see if the tests pass on version 3.5.2?

Alternatively you can upgrade Maven as part of your build, see https://github.com/apache/storm/blob/38b09fd229d2034a0fb6d5359eaa0b8ecdc0b61a/.travis.yml#L46

**Comment by brabenetz** [comment]
@srdo
FYI, I found out why your build run with maven 3.5.4
You using "mvnw" script in your root-repo (travic-ci detects that and uses it), which will download the exact version 3.5.4 (This maybe slow down your build).

I will just wait until travis-ci updates there images, and update the license-maven-plugin later.
thanks.
