### ISSUE TITLE
Plans for 1.21 release

### ISSUE THREAD

**Issue by srdo** [mojohaus/license-maven-plugin#338]
Hi,

Any chance 1.21 gets released soon? It would be nice to get https://github.com/mojohaus/license-maven-plugin/pull/325 out, it's breaking one of my builds.

Thanks for your efforts btw.

**Comment by ppalaga** [comment]
I'd do it in a couple of days, ideally after merging @digulla 's PR for https://github.com/mojohaus/license-maven-plugin/issues/337

It is going to be major++ because now we require Maven 3.5.0+.

**Comment by srdo** [comment]
Sounds good, thanks.

**Comment by ppalaga** [comment]
I am about to release.

**Comment by ppalaga** [comment]
Release voting is open https://groups.google.com/forum/#!topic/mojohaus-dev/bdKRUDPztI4
