### ISSUE TITLE
Missing Version 2.0.0 in Maven-Central

### ISSUE THREAD

**Issue by mazze5** [mojohaus/license-maven-plugin#343]
Hi,
I can't find version 2.0.0 in the maven central. Only version 1.20.0 is available https://search.maven.org/search?q=g:org.codehaus.mojo%20a:license-maven-plugin

**Comment by ppalaga** [comment]
Sorry, I forgot to hit the button in oss.sonatype.org after the voting was over, because I am on travel. Done it now the artifacts should become visble on Maven Central within ~40mins. Thanks for reminding me.
