### ISSUE TITLE
Question: how to define <extraExtensions> for files without file extension

### ISSUE THREAD

**Issue by heapifyman** [mojohaus/license-maven-plugin#38]
How would I define `<extraExtensions>` for a file that does not have a file extension, like e.g. `Dockerfile`?

Or is `Dockerfile` covered by any one of the default ones?

**Comment by tchemit** [comment]
@heapifyman AFAICR this is not possible easily on this version. I will have a closer look on this new feature.

**Comment by tchemit** [comment]
I move this feature to backlog, for sure won't be done for version 1.10.

**Comment by tchemit** [comment]
@heapifyman Ok this is now possible using the new extraFiles parameter. for each of your file, let define the associated comment style to apply.
