### ISSUE TITLE
Possibility to exclude own dependencies in download-licenses goal

### ISSUE THREAD

**Issue by Matze2** [mojohaus/license-maven-plugin#40]
Our own artifacts do not have any license information which leads to false warnings like
[WARNING] POM for dependency <our-group-id1>:<our-artifact1> has an invalid license URL: null
[WARNING] No license information available for: <our-group-id2>:<our-artifact2>

While this is only a cosmetic issue it might happen that real warnings about missing license of foreign components get overseen.

It would be nice to have some exclude possibilities similar to add-third-party.
For us having &lt;excludedGroups> and &lt;excludedLicenses> (if this is possible) would help a lot.

Thank you very much that development continues for this useful plugin!

**Comment by Matze2** [comment]
I gave it a quick try and added an "excludedGroups" property in AbstractDownloadLicensesMojo class and adjusted the getter and it immediately worked that we could exclude our own groups by regexp pattern for download-licenses goal.
So the existing code is already 99% prepared for that.

**Comment by tchemit** [comment]
@Matze2 Ok I have just implements for (include/exclude) for scopes, groupIds and artifactIds.

Have a look to [it ISSUE-40](https://github.com/mojohaus/license-maven-plugin/tree/master/src/it/ISSUE-40) for configuration.
