### ISSUE TITLE
third-party-report.html not well formed

### ISSUE THREAD

**Issue by etschelp** [mojohaus/license-maven-plugin#400]
I want to apply a xslt transformation to the html report, unfortunately this is not possible because of a missing `</td>`. The fix is actually quite simple. Add the following to line 217 of the AbstractLicenseReportRenderer.java

```java
        sink.tableCell_();
```

**Comment by slawekjaranowski** [comment]
Is it still valid? 

Fix looks a simple ... please create PR.
