### ISSUE TITLE
aggregate-add-third-party vs add-third-party in multi-module builds

### ISSUE THREAD

**Issue by hashhar** [mojohaus/license-maven-plugin#409]
I have a multi-module project where I have a parent pom and a submodule that aggregates relevant modules for the final artifact.

If I want to generate a single license.xml and a directory containing all of the licenses then how can I do that?

`add-third-party` doesn't seem to work in projects where you have your packaging format and not all dependencies are directly listed in the pom.xml.

From what I understand the `aggregate-add-third-party` goal just forks an execution for each submodule of the module I run the build from. But it creates the files as a resource of each submodule instead of as a resource of the aggregator project.

How can I "aggregate" the license information from all modules into the final artifact?

**Comment by duracotton** [comment]
same question here, any solution / suitable optional parameter for that scenario?

**Comment by hashhar** [comment]
I had to change the submodule that aggregates the individual modules to explicitly list the dependencies in pom.xml. Then `add-third-party` did what I wanted.

It's unfortunate that it requires changing the pom.xml to explicitly list dependencies but it works.
