### ISSUE TITLE
Ability to override/correct/clarify third party licenses 

### ISSUE THREAD

**Issue by ntdaley** [mojohaus/license-maven-plugin#41]
There are two use cases where I would like to be able to override the license(s) specified by a dependency's pom.

(I do of course recognise that this has potential for misuse, to produce results attributing the wrong license)

Some dependencies list multiple licenses, because they are dual licensed.  i.e. I have a choice between which license I use.
For this case, I would like to be able to specify which license I have chosen to use.  (So that if I blacklisted one of the other licenses, it won't fail my build.)
You could mitigate some risk by requiring that the overridden license match one of the licenses provided by the dependency pom.  (Though this would not address risk from assuming that a dependency with multiple licenses is dual-licensed, as opposed to having parts under one license, parts under another license.)

Some dependencies are not completely precise in identifying the license.  e.g. The pom for the dependency might say it's the BSD license, without indicating which variant... 2-clause, 3-clause, 4-clause, some other variant.
For this case, I would like to be able to correct for example a dependency that says it uses a BSD license, to show that it specifically uses the BSD-3-Clause license.  This is so that I can more easily use the output of this plugin to identify license obligations for various dependencies.
You could mitigate some risk by requiring that the overridden license have as a prefix-string one of the licenses specified by the dependency pom.  The plugin's existing licenseMerges functionality could then be used if necessary to turn it into something saner.
e.g. If the dependency specified `<license>BSD License</license>`, I could override that to `<license>BSD License - 3 Clause</license>` (because 'BSD License' is a prefix of 'BSD License - 3 Clause'), and then use licenseMerges: `<licenseMerge>BSD-3-Clause|BSD License - 3 Clause</licenseMerge>`

Something like the existing 'missing files' functionality could be a good way to do this, but:
- at present they will be ignored for dependencies that specify a license
- it may be worth keeping licenses being overridden separate, to make it easier to give them greater scrutiny.

**Comment by steveash** [comment]
I especially agree with the filtering of excluded licenses from dual licensed artifacts. If it's dual licensed and one of the licenses is excluded/forbidden then don't output it in the report.

**Comment by TorstenKruse** [comment]
We struggled about dual licensed dependencies too. Would be quite nice if the plugin could handle this.

**Comment by ercpe** [comment]
Should be solved with PR 52 (https://github.com/mojohaus/license-maven-plugin/pull/52)
