### ISSUE TITLE
aggregate-add-third-party goal has no groupByLicense option

### ISSUE THREAD

**Issue by solomax** [mojohaus/license-maven-plugin#43]
I believe it would be good idea to add "groupByLicense" option to "aggregate-add-third-party" goal

**Comment by tchemit** [comment]
@solomax In fact you can change the template to generate the third-party file for this purpose.

Try to set (in properties section)
```
<license.fileTemplate>/org/codehaus/mojo/license/third-party-file-groupByLicense.ftl</license.fileTemplate>
```

**Comment by solomax** [comment]
@tchemit just have tried and it doesn't help :(
Are there any other options?

**Comment by solomax** [comment]
@tchemit `excludedScopes` option also would be helpful

**Comment by solomax** [comment]
I believe this issue need to be reopened

**Comment by tchemit** [comment]
@solomax what happened when you tried with the other template ?

**Comment by solomax** [comment]
I have added
```
<license.fileTemplate>/org/codehaus/mojo/license/third-party-file-groupByLicense.ftl</license.fileTemplate>
```
nothing changed
It seems artifacts are being grouped by module, final grouping is missing

**Comment by tchemit** [comment]
Hum, let me check that again.

**Comment by tchemit** [comment]
Ok in fact `license.filteTemplate` is to put in properties section, toehrwise in plugin configuration you must use `filteTemplate` and it produces this result : 

List of third-party dependencies grouped by their license type.

    Apache License, Version 2.0:

        * Apache Commons Lang (org.apache.commons:commons-lang3:3.5 - http://commons.apache.org/proper/commons-lang/)
        * multimodule-with-war-web (org.apache.multimodule-with-war:multimodule-with-war-web:1.0.0-SNAPSHOT - http://maven.apache.org)

    Common Public License Version 1.0:

        * JUnit (junit:junit:3.8.1 - http://junit.org)

    The Apache Software License, Version 2.0:

        * Apache Commons Logging (commons-logging:commons-logging:1.2 - http://commons.apache.org/proper/commons-logging/)
        * StAX API (stax:stax-api:1.0.1 - http://stax.codehaus.org/)

    Unknown license:

        * StAX (stax:stax:1.2.0 - http://stax.codehaus.org/)

    http://asm.ow2.org/license.html:

        * Apache XBean :: ASM 5 shaded (repackaged) (org.apache.xbean:xbean-asm5-shaded:3.17 - http://geronimo.apache.org/maven/xbean/3.17/xbean-asm5-shaded)

    http://www.apache.org/licenses/LICENSE-2.0.txt:

        * Apache XBean :: ASM 5 shaded (repackaged) (org.apache.xbean:xbean-asm5-shaded:3.17 - http://geronimo.apache.org/maven/xbean/3.17/xbean-asm5-shaded)
``
``

**Comment by tchemit** [comment]
@solomax Is it ok for you ?

**Comment by tchemit** [comment]
Plugin configuration to use:
``
<plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>license-maven-plugin</artifactId>
        <version>1.13</version>
        <executions>
          <execution>
            <id>download-licenses</id>
            <goals>
              <goal>aggregate-add-third-party</goal>
            </goals>
            <configuration>
              <useMissingFile>true</useMissingFile>
              <fileTemplate>/org/codehaus/mojo/license/third-party-file-groupByLicense.ftl</fileTemplate>
            </configuration>
          </execution>
        </executions>
      </plugin>
``

**Comment by solomax** [comment]
@tchemit just have checked
works as expected, thanks for your help!

Should I file separate issues regarding `excludedScopes` and `no-fork`?

I have multiple
```
[INFO] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[INFO] Forking Openmeetings Screen Sharing applet 4.0.0-SNAPSHOT
[INFO] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[INFO] 
[INFO] --- license-maven-plugin:1.13:add-third-party (add-third-party) @ openmeetings-screenshare ---
[INFO] All files are up to date, skip goal execution.
```
And I belive `no-fork` mode might help a lot

**Comment by tchemit** [comment]
Yes please do separate issues :)

**Comment by solomax** [comment]
Done, Thanks!
