### ISSUE TITLE
aggregate-add-third-party fails on multimodule project

### ISSUE THREAD

**Issue by solomax** [mojohaus/license-maven-plugin#45]
aggregate-add-third-party fails on multi-module project in case it was never build on the machine

in case project has following structure

parent
   child A
   child B (dependent on "child A")

since aggregate-add-third-party being run during generate sources phase no subprojects are build
the whole build fails

original report [1]

[1] http://markmail.org/message/qgiuuzhc6admkzpd

**Comment by tchemit** [comment]
I can only suggest you to build once before using this plugin. I can't figure out any solution in this project for this problem.
I will close the issue, since I won't fix it. Thanks.

**Comment by simonklb** [comment]
I'm facing the same issue, I don't think this should be discarded as a minor issue though. For example, it's quite common to have automatic builds on a CI system where the project is being built for the first time. It's not really reasonable to make the solution be "manual builds without the plugin enabled first and then build normally".

My initial thought when looking at the options was that the `exclude*` options would cause the plugin to skip the dependencies entirely, not simply remove them from the output. Is it not possible to exclude the evaluation of certain dependencies in maven?

**Comment by tchemit** [comment]
@simonklb There is plenty of solutions I think.

What about to put your license plugin invocation in a profile and execute this profile only if the last module /target exist ? or in a maven local repository ?
This should works, no ?

**Comment by tchemit** [comment]
@solomax 
I can recommand you to us something like this:

```
    <profile>
      <id>execute-license-plugin</id>
      <activation>
        <file>
          <exists>${user.home}/.m2/repository/org/apache/multimodule-with-war/multimodule-with-war-web/maven-metadata-local.xml</exists>
        </file>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>license-maven-plugin</artifactId>
            <version>1.14-SNAPSHOT</version>
            <executions>
              <execution>
                <id>download-licenses</id>
                <goals>
                  <goal>aggregate-add-third-party</goal>
                </goals>
                <configuration>
                  <useMissingFile>true</useMissingFile>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
```

**Comment by simonklb** [comment]
I believe we solved this by adding the license plugin to the build of certain sub-modules rather than in the root pom.

**Comment by tchemit** [comment]
The solution I just describe above is working, still this is a nice gentle hack :).

**Comment by simonklb** [comment]
Oh yea, and we used `add-third-party` only, and not `aggregate-add-third-party`.
