### ISSUE TITLE
Why attaching the 'missing' file instead of the 'THIRD-PARTY' file

### ISSUE THREAD

**Issue by fmarot** [mojohaus/license-maven-plugin#47]
I've just realized that the plugin allows to deploy the 'missing' file using 'deployMissingFile' option, but does not allow to deploy the 'third-party' file that is generated and contains the info about the licenses used.
I found it so strange ! Why would one deploy the former instead of the latter ?
Maybe I misunderstood something ;)

For the record, here is an exerpt from my config but I don't think it will help you...
```

				<configuration>
					<thirdPartyFilename>myProject-${project.version}-THIRD-PARTY.html</thirdPartyFilename>
					<deployMissingFile>true</deployMissingFile>	<!-- warning: may be deployed even if skipAttach=true (see config of build-helper-maven-plugin) -->
					<failIfWarning>true</failIfWarning>
					<excludedGroups>com.myCompany.*</excludedGroups>
					<useMissingFile>true</useMissingFile>
					<missingFile>src/license/THIRD-PARTY.properties</missingFile>
					<fileTemplate>${project.basedir}/src/license/license-template.ftl</fileTemplate>
					<licenseMerges>
...
					</licenseMerges>

```

**Comment by tchemit** [comment]
Missing files help to build other projects third party files, they need to be deployed.
Third party files can't help for building other maven project, so I don't see the point to deploy them.
You can still do this by yourself in your project. I close this issue since I won't fix it. thanks.

**Comment by fmarot** [comment]
OK, thanks for the info, I understand better now !
