### ISSUE TITLE
Multi-module build sharing single missing file overwrites missing file every time

### ISSUE THREAD

**Issue by steveash** [mojohaus/license-maven-plugin#48]
Hello I have a multi-module build like this:

```
- pom.xml
- src/license/THIRD-PARTY.properties
- childA/
-- pom.xml
- childB/
-- pom.xml
```

And I configured the root pom.xml like this:

``` xml
<plugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>license-maven-plugin</artifactId>
  <version>1.9</version>
  <configuration>
    <excludedScopes>test</excludedScopes>
    <includeTransitiveDependencies>true</includeTransitiveDependencies>
    <useMissingFile>true</useMissingFile>
    <missingFile>${session.executionRootDirectory}/src/license/THIRD-PARTY.properties</missingFile>
  </configuration>
  <executions>
    <execution>
      <id>add-third-party</id>
    </execution>
  </executions>
</plugin>
```

Running `license:aggregate-add-third-party` from the root did produce an aggregated file -- but it overwrote my root src/license/THIRD-PARTY.properties file.  From the log output it looks like the first child project detected it correctly but the subsequent children overwrote it for some reason.

Is this intended? Is there a way to enable the missing file from a global location like this but turn off the auto-writing of records to it?

**Comment by pgmillon** [comment]
Same issue here, any updates ?

**Comment by pgmillon** [comment]
I think the issue is related to this: https://github.com/mojohaus/license-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/license/AddThirdPartyMojo.java#L262

**Comment by wardvijf** [comment]
@pgmillon @steveash I don't know if this is what you're looking for, but take a look at this PR I just created https://github.com/mojohaus/license-maven-plugin/pull/64
