### ISSUE TITLE
m2e warns "Plugin execution not covered by lifecycle configuration"

### ISSUE THREAD

**Issue by sewe** [mojohaus/license-maven-plugin#53]
Eclipse m2e warns about [this](https://www.eclipse.org/m2e/documentation/m2e-execution-not-covered.html) at least for the `license:update-project-license` goal (but probably also others).

(FWIW, as `license:update-project-license` generates resources, simply ignoring it during the build may not be desired.)

**Comment by tchemit** [comment]
Something has be done for you eclipse guys (See #17). Hopes it will help you. If not please give us more input to fix you problem. I will close the issue, since I really do not know what to do for you. thanks.
