### ISSUE TITLE
MAVEN 3.9.2: Validation failure

### ISSUE THREAD

**Issue by AndreasIgelCC** [mojohaus/license-maven-plugin#572]
We started to analyse all maven-plugins if they are prepared for maven4. You can gain this with 
`mvn license:aggregate-third-party-report -Dmaven.plugin.validation=verbose` 
and by using a maven-version in 3.9.2 or above. For license-maven-plugin the validation returns the following warnings:

[WARNING]  * org.codehaus.mojo:license-maven-plugin:2.4.0
[WARNING]   Declared at location(s):
[WARNING]    * unknown
[WARNING]   Mojo EXTERNAL issue(s):
[WARNING]    * Mojo license:aggregate-third-party-report (org.codehaus.mojo.license.AggregatorThirdPartyReportMojo)
[WARNING]      - Parameter 'localRepository' uses deprecated parameter expression '${localRepository}': ArtifactRepository type is deprecated and its use in Mojos should be avoided.

**Comment by AndreasIgelCC** [comment]
Would it be possible, that you @slawekjaranowski have a look on that?

**Comment by slawekjaranowski** [comment]
It is from reporting / doxia api we need switch to 2.x

https://cwiki.apache.org/confluence/display/MAVEN/Towards+Doxia+2.0.0+Stack#TowardsDoxia2.0.0Stack-Progress

**Comment by AndreasIgelCC** [comment]
Is that switch planned and do you have time to do that? Or do you need help with it?

**Comment by slawekjaranowski** [comment]
Doxia 2.x is under preparing
https://lists.apache.org/thread/l778r6cwj604hxhjlqs8kt58nngcd602
