### ISSUE TITLE
Allow using the current year in templates.

### ISSUE THREAD

**Issue by ST-DDT** [mojohaus/license-maven-plugin#58]
I would like to create a license template similar to this one:

> This file is part of MyLib, licensed under the MIT License (MIT).
>
> Copyright (c) MyLib Authors (${inceptionYear} - ${currentYear})

Expected result:

> This file is part of MyLib, licensed under the MIT License (MIT).
>
> Copyright (c) MyLib Authors (2015 - 2016)

I know, that I can just hardcode the current year, as it does not change very often,
but I keep forgetting it if I just create a minor fix in a project.

**Comment by mpkorstanje** [comment]
It already does this. Though the copy right notice comes before the year. You do set canUpdateCopyright to true in the configuration.

For example see: 

https://github.com/Simmetrics/simmetrics/blob/master/simmetrics-core/src/main/java/org/simmetrics/Distance.java
