### ISSUE TITLE
Override the identified license?

### ISSUE THREAD

**Issue by johnament** [mojohaus/license-maven-plugin#59]
Our project has dependencies on a number of open source projects.  Using the license plugin generates the following call out:

```
        Public Domain:

            * AOP alliance (aopalliance:aopalliance:1.0 - http://aopalliance.sourceforge.net)
            * XNIO API (org.jboss.xnio:xnio-api:3.3.6.Final - http://www.jboss.org/xnio)
            * XNIO NIO Implementation (org.jboss.xnio:xnio-nio:3.3.6.Final - http://www.jboss.org/xnio-all/xnio-nio)
```

AOP alliance is Public Domain, however XNIO is not.  XNIO is in fact apache license.  https://github.com/dmlloyd/xnio/blob/3.3.6.Final/LICENSE.txt  I was wondering if there's a way to override the selected license?  It seems to be coming from the parent pom, https://github.com/jboss/jboss-parent-pom/blob/master/pom.xml#L53

**Comment by mpkorstanje** [comment]
I don't believe there is. The current options all relate to missing licenses. 

The problem with XNIO seems to be that the project did not override the license section from the parent pom. You may wish to consider a pull request against XNIO to fix that.

**Comment by danielwegener** [comment]
I still think it would be important to be able overwrite certain artifact licenses (and maybe the URLs to these licenses too).

Sometimes you can not simply create a pull request for an ten year old but super common dependency that are not plain github projects but come somewhere out of a big company where you do not even know how to start finding someone who could fix the license and publish a new release.

My current favourite example:
```
[WARNING] There are 1 forbidden licenses used:
[WARNING] License license.txt used by 1 dependencies:
 -JPA 2.0 API (org.hibernate.javax.persistence:hibernate-jpa-2.0-api:1.0.1.Final - http://hibernate.org)
```

My suggestion: Let the THIRD-PARTY.properties also override defined licenses (or at least add one in the sense of #52).

**Comment by johnament** [comment]
I do plan to raise a PR to this plugin to support overrides.  In addition to your comment, there are cases for dual licensed software.  In both open source and commercial use cases, you need to declare the license in use (read the CDDL/GPL dual license very closely).  

I've just been heads down on making my local format correct to know what overrides need to look like.

**Comment by pgmillon** [comment]
Hey, seems cool. Any updates on this ?

**Comment by tchemit** [comment]
I just code this. You can add extra license information in the ``Override file`` which is a properties file.
 The format of the file is the same than the ``missing file``.

Enjoy.

**Comment by danielwegener** [comment]
Great stuff! Thanks alot!
Any idea when 1.12 will pop up in central?

**Comment by tchemit** [comment]
In two days now, the release process requires at least 72 hours.

**Comment by danielwegener** [comment]
@tchemit Do i understand it correctly that overrides from the `override-THIRD-PARTY.properties` are not applied during license check in 1.12?

I get the following error (with `<failIfWarning>` is `true`):
```
[WARNING] There are 1 forbidden licenses used:
[WARNING] License CDDL + GPLv2 with classpath exception used by 1 dependencies:
 -javax.transaction API (javax.transaction:javax.transaction-api:1.2 - http://jta-spec.java.net)
```
Now I have created the file `my-proj/src/license/override-THIRD-PARTY.properties` with the following content:
```
# original: CDDL + GPLv2 with classpath exception
javax.transaction--javax.transaction-api--1.2=BSD-3-Clause
```
... while my project pom has an whitelist entry for `BSD-3-CLAUSE`:
```
<configuration>
 <includedLicenses>
   <includedLicense>BSD-3-Clause</includedLicense>
```

However, the build still fails with the same error as shown above.
