### ISSUE TITLE
Feature request: Add aggregate-third-party-report

### ISSUE THREAD

**Issue by AstridS** [mojohaus/license-maven-plugin#6]
Hi everybody,
we are using this plugin for multi module maven projects. The goal aggregate-add-third-party works great and generates the aggregated THIRD-PARTY.txt.
It would be wonderful to have an aggregate-third-party-report also: an HTML version of the aggregated THIRD-PARTY.txt
Please consider implementing this new report.
Kind regards,
Astrid

**Comment by tchemit** [comment]
@AstridS I will have a look at this soon. thanks for idea.

**Comment by matt-shaw** [comment]
I would also like this feature.  It would be great to have it fully integrated into a site report.
