### ISSUE TITLE
Transitive Dependencies

### ISSUE THREAD

**Issue by annatara1** [mojohaus/license-maven-plugin#60]
Hi,

I was wondering why transitive dependencies do not show up in the html output of executing the third-party-report goal? Thanks!

**Comment by tchemit** [comment]
Hi @annatara1 , could you provide us a little project that prove the defect ? thanks.

**Comment by tchemit** [comment]
Something was added to remove transitive dependencies of the excluded artifacts (See #82), is this could help you ?

**Comment by tchemit** [comment]
I just try it out on some projects, and I get all transitives dependencies.
I will close this issue. Feel free to give us more info about your problem...
