### ISSUE TITLE
Build fails for certificate violation

### ISSUE THREAD

**Issue by rchargel** [mojohaus/license-maven-plugin#61]
I am trying to build the license-maven-plugin, but I get a failed build with an error in the integration test PR-32/pom.xml

The error is as follows:

    [WARNING] Unable to retrieve license for dependency: org.codehaus.mojo.license.test:PR-32-child1
    [WARNING] https://jaxx.nuiton.org/v/latest/license.html
    [WARNING] sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

This then causes the validation groovy script to fail because the license file isn't written.

This seems to be caused by the fact that the URL https://jaxx.nuiton.org uses a certificate that is not in Java's trusted list of certificates.

Do you have a fix for this?

**Comment by tchemit** [comment]
Thanks for the patch @pgmillon .
