### ISSUE TITLE
Prevent formatting of licence headers in java files

### ISSUE THREAD

**Issue by mpkorstanje** [mojohaus/license-maven-plugin#7]
You can prevent formatting of licence headers in java files using the start tag `/*-` rather then `/*`. This would avoid the need to either run maven before each commit, or for custom formatting setting to exclude the header from formatting - or suffer the superfluous changes in the commit log.

```java
/*-
 * Here is a block comment with some very special
 * formatting that I want indent(1) to ignore.
 *
 *    one
 *        two
 *            three
 */
```
It seems to be part of the Java standard but I couldn't find any recent sources on short notice. At the very least the formatter in Eclipse obeys this. 

 * http://stackoverflow.com/questions/1024886/making-eclipses-java-code-formatter-ignore-comments
 * http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-141999.html#350

Also looks like a fairly trivial change to JavaFileHeaderTransformer.java

**Comment by tchemit** [comment]
@mpkorstanje you can use now `useJavaNoReformatCommentStartTag`  in plugin configuration to get `/*-` comment start tag for java files.

**Comment by mpkorstanje** [comment]
Much obliged.
