### ISSUE TITLE
Class not found on mvn license:aggregate-third-party-report

### ISSUE THREAD

**Issue by Jessevanbekkum** [mojohaus/license-maven-plugin#73]
When I try to run `mvn license:aggregate-third-party-report` I get a build failure, with the following error:
`
Failed to execute goal org.codehaus.mojo:license-maven-plugin:1.12:aggregate-third-party-report (default-cli) on project ing-securities: Execution default-cli of goal org.codehaus.mojo:license-maven-plugin:1.12:aggregate-third-party-report failed: A required class was missing while executing org.codehaus.mojo:license-maven-plugin:1.12:aggregate-third-party-report: org/apache/maven/doxia/sink/render/RenderingContext
`

This is probably the same issue as https://github.com/mojohaus/license-maven-plugin/issues/69.

That issue was closed, but I think there still is something wrong here. I downloaded the doxia jars from maven central (http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.apache.maven.doxia%22%20AND%20a%3A%22doxia-core%22) and starting with version 1.5, the file org/apache/maven/doxia/sink/render/RenderingContext.class is not available anymore in the jar.

I was able to to get it working by adding this to my plugin definition:
```xml
          <dependencies>
            <dependency>
              <groupId>org.apache.maven.doxia</groupId>
              <artifactId>doxia-core</artifactId>
              <version>1.4</version>
            </dependency>
          </dependencies>
```
Here is a part of the stacktrace:

```
Error injecting: org.apache.maven.doxia.siterenderer.DefaultSiteRenderer
java.lang.ClassNotFoundException: org.apache.maven.doxia.sink.render.RenderingContext
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50) ~[plexus-classworlds-2.5.2.jar:na]
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271) ~[plexus-classworlds-2.5.2.jar:na]
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247) ~[plexus-classworlds-2.5.2.jar:na]
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239) ~[plexus-classworlds-2.5.2.jar:na]
	... 93 common frames omitted
Wrapped by: java.lang.NoClassDefFoundError: org/apache/maven/doxia/sink/render/RenderingContext
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_101]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_101]
	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_101]
```

**Comment by MacGyves** [comment]
This also happens when executing mvn license:third-party-report. 

The workaround about adding doxia-core as plugin dependency worked for me, too.

**Comment by bannmann** [comment]
I have the same issue, and the workaround "fixes" the problem.

**Comment by tchemit** [comment]
Hi guys,

Which version of maven-site-plugin ae you using ?

**Comment by dhalperi** [comment]
Hi @tchemit I am getting this error with version 1.13:

```
➜  projects git:(maven-ify) ✗ mvn license:aggregate-third-party-report
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Batfish
[INFO] batfish-common-protocol
[INFO] batfish
[INFO] batfish-client
[INFO] coordinator
[INFO] allinone
[INFO] question
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Batfish 0.29.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- license-maven-plugin:1.13:aggregate-third-party-report (default-cli) @ batfish-parent ---
[WARNING] Error injecting: org.apache.maven.doxia.siterenderer.DefaultSiteRenderer
java.lang.NoClassDefFoundError: org/apache/maven/doxia/sink/render/RenderingContext
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:688)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:380)
	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:164)
```

**Comment by MacGyves** [comment]
I'm on maven 3.3.9 and license-maven-plugin 1.12

**Comment by kajh** [comment]
We get the folloing stacktrace after adding the license-maven-plugin as
`<plugin>
   <groupId>org.codehaus.mojo</groupId>
   <artifactId>license-maven-plugin</artifactId>
   <version>1.16</version>
</plugin>`
We use maven-site-plugin 3.7.1.

`[WARNING] An issue has occurred with license-maven-plugin:1.16:third-party-report report, skipping LinkageError org/apache/maven/doxia/sink/SinkEventAttributeSet, please report an issue to Maven dev team.
java.lang.NoClassDefFoundError: org/apache/maven/doxia/sink/SinkEventAttributeSet
	at org.codehaus.mojo.license.AbstractLicenseReportRenderer.sinkHeaderCellText(AbstractLicenseReportRenderer.java:176)`

I added doxia-core and doxia-site-renderer as jacobwil described.

Any ideas? Thanks!

:)

**Comment by ispringer** [comment]
Why was this closed?

**Comment by tchemit** [comment]
A mistake I suppose :( I will have a look at it soon.--Enjoy and ShareTony Chemit
          
            
            On nov. 9 2018, at 9:00 pm, Ian Springer <notifications@github.com> wrote:
            
            
              Why was this closed?

**Comment by vasiliy-bout** [comment]
I've just tried to use the latest version 1.16, and the problem still persists. It was reported on version 1.12. Please, fix it. Can you just add this dependency into the plugin's pom.xml?

**Comment by ptahchiev** [comment]
They need to update the doxia-site-renderer from 1.4 to 1.8.1 - i don't know why they are not doing it.

**Comment by digulla** [comment]
With license-maven-plugin:1.16:aggregate-third-party-report, doxia 1.8 doesn't work for me.
I had to use doxia 1.6 as in https://github.com/mojohaus/license-maven-plugin/issues/73#issuecomment-346130508

With doxia 1.8 and 1.8.1, org/apache/maven/doxia/sink/SinkEventAttributeSet is missing (probably was moved to a new package org.apache.maven.doxia.sink.impl in 1.8).

**Comment by ppalaga** [comment]
A pull request with an integration test is welcome.
