### ISSUE TITLE
Generate licenses.xml from license:download-licenses without downloading any licenses

### ISSUE THREAD

**Issue by eirikb** [mojohaus/license-maven-plugin#76]
Is it possible to get only the file generated by [LicenseSummaryWriter.writeLicenseSummary](https://github.com/mojohaus/license-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/license/utils/LicenseSummaryWriter.java#L52) without having to download any licenses?  
Or to generate a similar file?

There is an [offline](http://www.mojohaus.org/license-maven-plugin/download-licenses-mojo.html#offline) optional parameter, but then [it won't generate](https://github.com/mojohaus/license-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/license/AbstractDownloadLicensesMojo.java#L251) the summary

We don't have internet connection when building, so we put our license files with semi-generic names into a folder, at _runtime_ we load the correct license file based on the license name.  
This is probably not a good solution, but for us it works fine, and we can control the license files and say they are text only (no html) as all of our license provide this.

**Comment by eirikb** [comment]
By using the `add-third-party` goal and using Regexp we are able to parse the _THIRD-PARTY.txt_-file and achieve a similar solution.

We might be doing something wrong, but we can't see any way to generate the summary XML file beside using the `download-licenses` goal.  
Proposing this PR as a possible fix:
https://github.com/mojohaus/license-maven-plugin/pull/79
It changes the `offline` flag from causing a skip of the whole goal, to not downloading the licenses.

**Comment by tchemit** [comment]
Fix by #79.
