### ISSUE TITLE
A required class was missing while executing org.codehaus.mojo:license-maven-plugin:1.12:update-file-header: org/apache/commons/logging/LogFactory

### ISSUE THREAD

**Issue by jennyindcs** [mojohaus/license-maven-plugin#78]
I tried to add license header to a Java project using the license-maven-plugin in the eclipse+maven environment.

The configuration of the license-maven-plugin in the pom.xml file looks like:

```xml
...
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>license-maven-plugin</artifactId>
    <version>1.12</version>
    <configuration>
        <verbose>false</verbose>
    </configuration>
    <executions>
        <execution>
            <id>generate-license-headers</id>
            <goals>
                <goal>update-file-header</goal>
            </goals>
            <phase>process-sources</phase>
            <configuration>
                <licenseName>Apache 2.0</licenseName>
                <roots>
                    <root>src/main/java</root>
                    <root>src/test/java</root>
                </roots>
             </configuration>
        </execution>
    </executions>
</plugin>
...
```

but I got the following error:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.378 s
[INFO] Finished at: 2017-03-03T15:25:02+00:00
[INFO] Final Memory: 11M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:1.12:update-file-header (generate-license-headers) on project taa: Execution generate-license-headers of goal org.codehaus.mojo:license-maven-plugin:1.12:update-file-header failed: A required class was missing while executing org.codehaus.mojo:license-maven-plugin:1.12:update-file-header: org/apache/commons/logging/LogFactory
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.codehaus.mojo:license-maven-plugin:1.12
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
...
[ERROR] urls[35] = file:/Users/xyz/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
[ERROR] urls[36] = file:/Users/xyz/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar
[ERROR] urls[37] = file:/Users/xyz/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar
[ERROR] urls[38] = file:/Users/xyz/.m2/repository/org/freemarker/freemarker/2.3.20/freemarker-2.3.20.jar
[ERROR] urls[39] = file:/Users/xyz/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.apache.commons.logging.LogFactory
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

I've checked the path listed above, the commons-logging-1.2.jar is in the maven local repository.
What may cause this error?

**Comment by tchemit** [comment]
@jennyindcs have you try to delete the repository directory ? and then relanch your build ?

**Comment by uvwild** [comment]
I did remove the local repository to no avail!
anyone else?

**Comment by uvwild** [comment]
The solution is to add additional dependencies to the plugin config.
This solves the missing class issue and moves on. 
I had to add 4 dependencies until it worked.
I think some older plugins are seriously messed up in terms of dependencies.

**Comment by ppalaga** [comment]
@uvwild please file a new issue if you see this happening with the newest license-maven-plugin version.
