### ISSUE TITLE
no-fork mode for aggregate-add-third-party

### ISSUE THREAD

**Issue by solomax** [mojohaus/license-maven-plugin#93]
I have multiple
```
[INFO] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[INFO] Forking Openmeetings Screen Sharing applet 4.0.0-SNAPSHOT
[INFO] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[INFO] 
[INFO] --- license-maven-plugin:1.13:add-third-party (add-third-party) @ openmeetings-screenshare ---
[INFO] All files are up to date, skip goal execution.
```
And I believe no-fork mode might help a lot

**Comment by qdoobp** [comment]
A no-fork mode for `aggregate-add-third-party` would help us too. We are unable to build with the License Plugin because it forks and tries to build modules for which the internal dependencies cannot be resolved. This is a big issue for us.

**Comment by 6d6566** [comment]
+1 

I need this switch as well. I can not resolve dependencies to modules in a multi-module project.

**Comment by tchemit** [comment]
Let's have a look to this new feature :).

**Comment by tchemit** [comment]
I just alos deprecated **aggregateMissingLicensesFileArtifact**, use now **missingLicensesFileArtifact** and
**aggregateMissingLicensesFile**, use now **missingLicensesFile**

**Comment by solomax** [comment]
Hello @tchemit, Thanks for the fix!
Unfortunately I'm unable to test it :( could you point me to the repository snapshots are published?

**Comment by tchemit** [comment]
there is a release in run :) 

See https://groups.google.com/forum/#!topic/mojohaus-dev/NXX0Ci0WLPs to get staging repository

**Comment by solomax** [comment]
Hello @tchemit, sorry for the late testing (I had no time before :((( )
It seems 1.14 breaks multi-module projects :((

Quickstart: https://github.com/solomax/multimodule-with-war
it works as expected in case `mvn clean install` is called
and fails with `Compilation failure` in case `mvn clean package -Pgenerate-third-party` is called

Could you please check it?

**Comment by solomax** [comment]
Hello @tchemit, could you please fix this plugin for multimodule project?
