### ISSUE TITLE
excludedScopes option is absent for aggregate-add-third-party

### ISSUE THREAD

**Issue by solomax** [mojohaus/license-maven-plugin#94]
I believe excludedScopes option is must have for aggregate-add-third-party goal

Could you please add it?

**Comment by tpeyrard** [comment]
In fact it works although it's not documented.
`mvn clean license:aggregate-add-third-party -Dlicense.excludedScopes=test` 
Make sure to prefix excludedScopes with `license`

**Comment by solomax** [comment]
Unfortunately it can't be used in `<configuration>` inside pom.xml :(

**Comment by tpeyrard** [comment]
I wanted to move all the command line options in a configuration tag today. I guess I'll do something else and stick to my command line arguments for the moment :)

**Comment by tchemit** [comment]
@Thomas, You can use it in the properties section :```<properties><license.excludedScopes>test</license.excludedScopes></properties>```--Enjoy and ShareTony Chemit
          
            
            On juil. 13 2017, at 9:29 am, Thomas <notifications@github.com> wrote:
            
            
              I wanted to move all the command line options in a configuration tag today. I guess I'll do something else and stick to my command line arguments for the moment :)

**Comment by tchemit** [comment]
@tpeyrard , yes it is not documented, in fact it calls the none aggregate goals, so all properties defined in none aggregate mojo should work here!

I will still add documentation about this point. thanks

**Comment by solomax** [comment]
Hello @tchemit,

unfortunately adding this
```
<properties>
    <license.excludedScopes>test</license.excludedScopes>
</properties>
```

doesn't help, test dependencies are being included into report

example: https://github.com/solomax/multimodule-with-war

**Comment by tchemit** [comment]
Hum @solomax , I will have a look then (I thought it would work...)

**Comment by tchemit** [comment]
@solomax , I just try and it works perflecty. I had a look to your project and I just saw you put the properties section into the plugin configuration section, that's not the good place.

The properties section is shared by all the project, See https://github.com/solomax/multimodule-with-war/pull/1.

I close this issue since it works :).

**Comment by solomax** [comment]
Thanks for the help with setting this up
I would expect to specify plugin properties at the plugin configuration section ..... But it's better than nothing :)

**Comment by tchemit** [comment]
With refactoring of aggregator mode (with no fork), this will possible in plugin configuration section.

**Comment by banterCZ** [comment]
Does not work for me with version `1.16`, I tried plugin configuration, properties and `-D` as well.
