### ISSUE TITLE
override license in aggregate-add-third-party goal

### ISSUE THREAD

**Issue by solomax** [mojohaus/license-maven-plugin#96]
It would be great to have the ability to override licence name per dependency and add license text (similar to #39 and #77)

**Comment by tchemit** [comment]
@solomax , this feature should be ok now with work in #93.

**Comment by solomax** [comment]
Hello @tchemit, would you be so kind to provide small example?
I would love to finally get something like this: https://github.com/apache/openmeetings/blob/master/LICENSE#L375

i.e.
jars
licence name(s)
Licence text


Thanks in advance!
