### ISSUE TITLE
Add failOnMissing and failOnBlacklisted instead of failOnWarning

### ISSUE THREAD

**Issue by ptahchiev** [mojohaus/license-maven-plugin#97]
Hey guys in my build I have set-up `failOnWarning` to `false` because maven brings dependencies with missing licenses like these:
````
[WARNING] There is 5 dependencies with no license :
[WARNING]  - dom4j--dom4j--1.6.1
[WARNING]  - javax.servlet--jstl--1.2
[WARNING]  - jgridshift--jgridshift--1.0
[WARNING]  - net.jcip--jcip-annotations--1.0
[WARNING]  - org.codehaus.jettison--jettison--1.2
````
However I have blacklisted the AGPL license and I really want to build to fail if I'm using dependency with this license. With the current setup I cannot do that. 

That's why I'm proposing two new properies: 

 - `failOnMissing` - fails the build if dependencies with missing license information is found.
 - `failOnBlacklist` - fails the build if dependencies from the blacklist are found.

**Comment by tchemit** [comment]
Nice idea, I will implement it, thanks.

**Comment by tchemit** [comment]
I just change the name of **failIfMissing* into **failOnMissing**.
