### ISSUE TITLE
outputDirectory doesn't aggregate files when used with license:aggregate-add-third-party

### ISSUE THREAD

**Issue by tpeyrard** [mojohaus/license-maven-plugin#98]
When using `outputDirectory` with `aggregate-add-third-party` goal I thought it would aggregates THIRD-PARTY.txt files of each submodules in one single file, in the specified directory.

`mvn clean license:aggregate-add-third-party -Dlicense.excludedScopes=test -Dlicense.outputDirectory=D:\tmp`

In `D:\tmp` there is a THIRD-PARTY.txt file that contains the licenses of the first module only.

Is it expected or a bug? 

Thanks

**Comment by tchemit** [comment]
@tpeyrard  : Nope that is NOT normal. I will have a look...

**Comment by tchemit** [comment]
I just introduce a new parameter **license.aggregateOutputDirectory** for this purpose.

I also remove the outputDirectory from the aggregate mojo.
